litrevu/litrevu/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


import authentication.views
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', authentication.views.login_page, name='login'),
    path('follow-users/', blog.views.follow_users, name='follow_users'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('my_blog/', blog.views.my_blog, name='my_blog'),
    path('home/', blog.views.home, name='home'),
    path('signup/', authentication.views.signup_page, name='signup'),
    path('photo/upload/', blog.views.photo_upload, name='photo_upload'),
    path('create_ticket_review/', blog.views.create_ticket_review, name='create_ticket_review'),
    path('ticket/create/', blog.views.ticket_and_photo_upload, name='ticket_create'),
    path('ticket/<int:ticket_id>', blog.views.view_ticket, name='view_ticket'),
    path('ticket/<int:ticket_id>/delete_ticket/', blog.views.delete_ticket, name='delete_ticket'),
    path('ticket/<int:ticket_id>/edit_ticket/', blog.views.edit_ticket, name='edit_ticket'),
    path('ticket/<int:ticket_id>/create_review/', blog.views.create_review, name='create_review'),
    path('ticket/delete_review/', blog.views.delete_review, name='delete_review'),
    path('review/<int:review_id>', blog.views.view_review, name='view_review'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrevu/blog/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models


class Photo(models.Model):
    image = models.ImageField()
    caption = models.CharField(max_length=128, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)


class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=1024)
    photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    has_review = models.BooleanField(default=False)


class Review(models.Model):
    title = models.CharField(max_length=128)
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    description = models.CharField(max_length=4096, blank=True)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

litrevu/blog/forms.py
from django import forms
from . import models
from django.contrib.auth import get_user_model

User = get_user_model()


class FollowUserForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur à suivre")

    def clean_username(self):
        username = self.cleaned_data['username']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError("Cet utilisateur n'existe pas.")
        return username


class PhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ['image', 'caption']


class TicketForm(forms.ModelForm):
    class Meta:
        model = models.Ticket
        fields = ['title', 'description']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = models.Review
        fields = ['title', 'description', 'rating']

litrevu/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import F, ExpressionWrapper, fields, Case, When
from django.urls import reverse
from authentication.models import User

from . import forms, models


@login_required
def my_blog(request):
    user = request.user
    photos = models.Photo.objects.all()
    tickets = models.Ticket.objects.filter(user=user)
    reviews = models.Review.objects.filter(user=user)

    context = {'photos': photos, 'tickets': tickets, 'user_name': user.username, 'reviews': reviews}
    return render(request, 'blog/my_blog.html', context)


@login_required
def home(request):
    user = request.user
    following_users = user.follows.all()
    tickets = models.Ticket.objects.filter(user__in=following_users).annotate(
        review_date=ExpressionWrapper(
            Case(
                When(review__isnull=False, then=F('review__date')),
                default=F('date'),
                output_field=fields.DateTimeField(),
            ),
            output_field=fields.DateTimeField()
        )
    ).order_by('-review_date')
    context = {'tickets': tickets}
    return render(request, 'blog/home.html', context)



@login_required
def photo_upload(request):
    form = forms.PhotoForm()
    if request.method == 'POST':
        form = forms.PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.uploader = request.user
            photo.save()
            return redirect('home')
    return render(request, 'blog/photo_upload.html', context={'form': form})


@login_required
def ticket_and_photo_upload(request):
    ticket_form = forms.TicketForm()
    photo_form = forms.PhotoForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST)
        photo_form = forms.PhotoForm(request.POST, request.FILES)
        if all([ticket_form.is_valid(), photo_form.is_valid()]):
            photo = photo_form.save(commit=False)
            photo.uploader = request.user
            photo.save()
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.photo = photo
            ticket.save()
            return redirect('home')

    return render(request, 'blog/create_ticket.html', context={'ticket_form': ticket_form, 'photo_form': photo_form,})


@login_required
def view_ticket(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    return render(request, 'blog/view_ticket.html', {'ticket': ticket})


@login_required
def edit_ticket(request, ticket_id):
    ticket = models.Ticket.objects.get(pk=ticket_id)
    ticket_form = forms.TicketForm(instance=ticket)
    photo_form = forms.PhotoForm(instance=ticket.photo)

    if request.user == ticket.user:
        if request.method == 'POST':
            ticket_form = forms.TicketForm(request.POST, instance=ticket)
            photo_form = forms.PhotoForm(request.POST, request.FILES, instance=ticket.photo)
            if ticket_form.is_valid():
                if all([ticket_form.is_valid(), photo_form.is_valid()]):
                    photo = photo_form.save(commit=False)
                    photo.uploader = request.user
                    photo.save()
                    ticket = ticket_form.save(commit=False)
                    ticket.user = request.user
                    ticket.photo = photo
                    ticket.save()
    else:
        return redirect('home')

    return render(request, 'blog/edit_ticket.html', context={'ticket_form': ticket_form, 'photo_form': photo_form, 'ticket': ticket})


@login_required
def delete_ticket(request, ticket_id):
    ticket = models.Ticket.objects.get(pk=ticket_id)
    if request.user == ticket.user:
        if request.method == 'POST':
            ticket.delete()
            return redirect('home')
    else:
        return redirect('home')

    return render(request, 'blog/delete_ticket.html', {'ticket': ticket})


@login_required
def create_review(request, ticket_id):
    ticket = models.Ticket.objects.get(pk=ticket_id)
    if models.Review.objects.filter(ticket=ticket).exists():
        return redirect('view_ticket', ticket_id=ticket_id)
    review_form = forms.ReviewForm()

    if request.method == 'POST':
        review_form = forms.ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.ticket = ticket
            review.user = request.user
            review.save()
            ticket.has_review = True
            ticket.save()
            return redirect('view_ticket', ticket_id=ticket_id)

    return render(request, 'blog/create_review.html', context={'review_form': review_form, 'ticket': ticket, })


@login_required
def delete_review(request, review_id):
    review = get_object_or_404(models.Review, id=review_id)
    if request.user == review.user:
        if request.method == 'POST':
            review.ticket.has_review = False
            review.ticket.save()
            review.delete()

            return redirect('home')
    else:
        return redirect('home')

    return render(request, 'blog/delete_review.html', {'review': review})


@login_required
def view_review(request, review_id):
    review = get_object_or_404(models.Review, id=review_id)
    return render(request, 'blog/view_review.html', {'review': review})


@login_required
def create_ticket_review(request):
    ticket_form = forms.TicketForm()
    photo_form = forms.PhotoForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST)
        photo_form = forms.PhotoForm(request.POST, request.FILES)
        if all([ticket_form.is_valid(), photo_form.is_valid()]):
            photo = photo_form.save(commit=False)
            photo.uploader = request.user
            photo.save()
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.photo = photo
            ticket.save()

            return redirect(reverse('create_review', kwargs={'ticket_id': ticket.id}))

    return render(request, 'blog/create_ticket_review.html', context={'ticket_form': ticket_form, 'photo_form': photo_form})


@login_required
def follow_users(request):
    following = request.user.follows.all()
    if request.method == 'POST':
        follow_user_form = forms.FollowUserForm(request.POST)
        if follow_user_form.is_valid():
            username = follow_user_form.cleaned_data['username']
            user_to_follow = User.objects.get(username=username)
            request.user.follows.add(user_to_follow)
            return redirect('home')

    if 'unfollow' in request.GET:
        user_to_unfollow_id = request.GET['unfollow']
        user_to_unfollow = User.objects.get(id=user_to_unfollow_id)
        request.user.follows.remove(user_to_unfollow)
        return redirect('home')

    follow_user_form = forms.FollowUserForm()
    return render(request, 'blog/follow_users_form.html', {'follow_user_form': follow_user_form, 'following': following,})

litrevu/blog/templates/blog/create_review.html
{% extends 'base.html' %}
{% block content %}
<div class="flex flex-col items-center space-y-4">
    <h2 class="text-2xl text-violet-800 mb-4">Écrire une Revue</h2>
    <form method="post" enctype="multipart/form-data">
        {{ review_form.as_p }}
        {% csrf_token %}
        <button class="block mt-1 bg-violet-500 hover:bg-violet-700 text-white font-bold py-2 px-4 border-b-4 border-violet-700 hover:border-violet-500 rounded" type="submit" >Publier</button>
    </form>
 <a href="{% url 'view_ticket' ticket_id=ticket.id %}" class="btn btn-secondary">Retour au ticket</a>
</div>
{% endblock content %}

litrevu/blog/templates/blog/create_ticket.html
{% extends 'base.html' %}
{% block content %}
<div class="flex flex-col items-center space-y-4">
    <h2 class="text-2xl text-violet-800 mb-4">Écrire un ticket</h2>
    <form method="post" enctype="multipart/form-data">
        {{ ticket_form.as_p }}
        {{ photo_form.as_p }}
        {% csrf_token %}
        <button class="block mt-1 bg-violet-500 hover:bg-violet-700 text-white font-bold py-2 px-4 border-b-4 border-violet-700 hover:border-violet-500 rounded" type="submit" >Publier</button>
    </form>
</div>
{% endblock content %}

litrevu/blog/templates/blog/create_ticket_review.html
{% extends 'base.html' %}
{% block content %}
<div class="flex flex-col items-center space-y-4">
    <h2 class="text-2xl text-violet-800 mb-4">Écrire un ticket puis une revue associée</h2>
    <form method="post" enctype="multipart/form-data">
        {{ ticket_form.as_p }}
        {{ photo_form.as_p }}
        {% csrf_token %}
        <button class="block mt-1 bg-violet-500 hover:bg-violet-700 text-white font-bold py-2 px-4 border-b-4
        border-violet-700 hover:border-violet-500 rounded" type="submit" >Publier votre ticket puis être rediriger pour la création de la revue associée</button>
    </form>
</div>
{% endblock content %}

litrevu/blog/templates/blog/delete_review.html
{% extends 'base.html' %}

{% block content %}
<div class="flex flex-col items-center space-y-4">
    <h1 class="text-2xl text-red-800 mb-4">Supprimer votre critique ?</h1>

    {% if request.method == 'POST' %}
    <p>La critique a été supprimé avec succès.</p>
    <a href="{% url 'home' %}">Retour à la page d'accueil</a>
    {% else %}
    <p>Êtes-vous sûr de vouloir supprimer votre critique ?</p>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Confirmer la suppression">
    </form>

    <a href="{% url 'home' %}">Annuler</a>
</div>
    {% endif %}
{% endblock %}

litrevu/blog/templates/blog/delete_ticket.html
{% extends 'base.html' %}

{% block content %}
<div class="flex flex-col items-center space-y-4">
    <h1 class="text-2xl font-bold text-red-500 mb-4">Supprimer votre ticket</h1>

    {% if request.method == 'POST' %}
    <p>Le ticket a été supprimé avec succès.</p>
    <a href="{% url 'home' %}">Retour à la page d'accueil</a>
    {% else %}
    <p>Êtes-vous sûr de vouloir supprimer votre ticket ?</p>

    <form method="post">
        {% csrf_token %}
        <button class="block mt-1 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-red-500 rounded" type="submit">
            Confirmer la suppression
        </button>
    </form>

    <a href="{% url 'home' %}">Annuler</a>
</div>
    {% endif %}
{% endblock %}

litrevu/blog/templates/blog/edit_ticket.html
{% extends 'base.html' %}
{% block content %}
<div class="flex flex-col items-center space-y-4">
    <h2  class="text-2xl text-violet-800 mb-4">Editer votre ticket</h2>
    <form method="post" enctype="multipart/form-data">
        {{ ticket_form.as_p }}
        {{ photo_form.as_p }}
        {% csrf_token %}
        <button type="submit">Valider les modifications</button>
    </form>
    <a href="{% url 'home' %}" class="button_comeback">Retour</a>
</div>
{% endblock %}

litrevu/blog/templates/blog/follow_users_form.html
{% extends 'base.html' %}
{% block content %}
<div class="flex flex-col items-center space-y-4">
    <h2 class="text-2xl text-violet-800 mb-4">Suivre des utilisateurs</h2>
    <form method="post">
        {{ follow_user_form.as_p }}
        {% csrf_token %}
        <button class="block mt-1 bg-violet-500 hover:bg-violet-700 text-white font-bold py-2 px-4 border-b-4 border-violet-700 hover:border-violet-500 rounded" type="submit" >Confirmer</button>
    </form>

        <h3>Utilisateurs suivis</h3>
        <ul>
            {% for user in following %}
                <li>{{ user.username }} <a class="text-red-500" href="?unfollow={{ user.id }}">Se désabonner</a></li>
            {% empty %}
                <li>Aucun utilisateur suivi.</li>
            {% endfor %}
        </ul>
</div>
{% endblock content %}

litrevu/blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
      <div class="flex flex-col items-center space-y-4">
          <h2 class="text-2xl text-violet-800">Flux</h2>
    {% for ticket in tickets %}
      {% if not ticket.has_review %}
        <a href="{% url 'view_ticket' ticket.id %}" class="text-center">
          <div class="w-1/2 mx-auto bg-white p-4 rounded-lg shadow-md flex items-center">
            <img src="{{ ticket.photo.image.url }}" alt="{{ ticket.title }}" class="w-1/3">
            <div class="ml-4">
              <h4 class="text-lg font-semibold mb-2">{{ ticket.title }}</h4>
              <p>{{ ticket.description }}</p>
              <p>Date de création : {{ ticket.date }}</p>
              <p>{{ ticket.user }}</p>
            </div>
          </div>
        </a>
      {% else %}
          <a href="{% url 'view_ticket' ticket.id %}" class="text-center">
                <div class="w-1/2 mx-auto bg-white p-4 rounded-lg shadow-md flex flex-col items-center">
                    {% for review in ticket.review_set.all %}
                        <div class="review w-full">
                            <h4 class="text-lg font-semibold mb-2">{{ review.title }}</h4>
                            <p>{{ review.description }}</p>
                            <p>Note: {{ review.rating }}/5</p>
                            <p>Date de création : {{ review.date }}</p>
                            <p>{{ review.user }}</p>
                        </div>
                    {% endfor %}

                    <a href="{% url 'view_ticket' ticket.id %}" class="text-center w-full">
                        <div class="flex items-center w-full">
                            <img src="{{ ticket.photo.image.url }}" alt="{{ ticket.title }}" class="w-1/3 h-auto">
                            <div class="ml-4">
                                <h4 class="text-lg font-semibold mb-2">{{ ticket.title }}</h4>
                                <p>{{ ticket.description }}</p>
                                <p>Date de création : {{ ticket.date }}</p>
                                <p>{{ ticket.user }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            </a>
      {% endif %}
    {% endfor %}
    </div>

{% endblock %}

litrevu/blog/templates/blog/my_blog.html
{% extends 'base.html' %}
{% block content %}
<div class="flex flex-col items-center space-y-4">
<h1 class="text-2xl text-violet-800 ">Bienvenue, {{ user_name }} !</h1>
    <a class="inline-block mt-1 bg-violet-500 hover:bg-violet-700 text-white font-bold py-2 px-4 border-b-4 border-violet-700 hover:border-violet-500 rounded" href="{% url 'create_ticket_review' %}" >Créer un ticket + revue</a>
<h4 class="text-1xl text-violet-800 mb-4">Ticket sans revue</h4>
<div class="flex flex-col items-center space-y-4">
    {% for ticket in tickets %}
        {% if not ticket.has_review %}
            <a href="{% url 'view_ticket' ticket.id %}" class="text-center">
                <div class="w-1/2 mx-auto bg-white p-4 rounded-lg shadow-md flex items-center">
                    <img src="{{ ticket.photo.image.url }}" alt="{{ ticket.title }}" class="w-1/3 h-auto">
                    <div class="ml-4">
                    <h4 class="text-lg font-semibold mb-2">{{ ticket.title }}</h4>
                    <p>{{ ticket.description }}</p>
                    </div>
                </div>
            </a>
        {% endif %}
    {% endfor %}
</div>

<h4 class="text-1xl text-violet-800 mb-4">Ticket avec revue</h4>
<div class="flex flex-col items-center space-y-4">
    {% for ticket in tickets %}
        {% if ticket.has_review %}

            <a href="{% url 'view_ticket' ticket.id %}" class="text-center">
                <div class="w-1/2 mx-auto bg-white p-4 rounded-lg shadow-md flex flex-col items-center">
                    {% for review in ticket.review_set.all %}
                        <div class="review w-full">
                            <h4 class="text-lg font-semibold mb-2">{{ review.title }}</h4>
                            <p>{{ review.description }}</p>
                            <p>Note: {{ review.rating }}</p>
                        </div>
                    {% endfor %}

                    <a href="{% url 'view_ticket' ticket.id %}" class="text-center w-full">
                        <div class="flex items-center w-full">
                            <img src="{{ ticket.photo.image.url }}" alt="{{ ticket.title }}" class="w-1/3 h-auto">
                            <div class="ml-4">
                                <h4 class="text-lg font-semibold mb-2">{{ ticket.title }}</h4>
                                <p>{{ ticket.description }}</p>
                            </div>
                        </div>
                    </a>
                </div>

            </a>
        {% endif %}
    {% endfor %}


</div>
</div>
{% endblock content %}

litrevu/blog/templates/blog/photo_upload.html
{% extends 'base.html' %}
{% block content %}
    <h2>Mettre en ligne une photo</h2>
    <form method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" >Publier</button>
    </form>
{% endblock content %}

litrevu/blog/templates/blog/view_review.html
{% extends 'base.html' %}
{% block content %}
<div class="flex flex-col items-center space-y-4">
    <h2 class="text-2xl text-violet-800 mb-4">{{ review.title }}</h2>
    <p>{{ review.description }}</p>
    <p>{{ review.ticket.title }}</p>
</div>
{% endblock content %}

litrevu/blog/templates/blog/view_ticket.html
{% extends 'base.html' %}
{% block content %}
<div class="flex flex-col items-center space-y-4">
    <div class="flex space-x-4">
        <div class="w-1/5">
            <img src="{{ ticket.photo.image.url }}" alt="{{ ticket.title }}">
        </div>
        <div class="w-2/3">
            <h2 class="text-2xl text-violet-800 mb-4">{{ ticket.title }}</h2>
            <p>{{ ticket.description }}</p>
        </div>
    </div>

    <div class="mt-4">
        {% if ticket.has_review == False %}
        <a href="{% url 'create_review' ticket_id=ticket.id %}" class="inline-block bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 border-b-4 border-green-700 hover:border-green-500 rounded">Créer une revue</a>
        {% endif %}

        {% if user == ticket.user %}
        <div class="flex space-x-4">
            <a href="{% url 'edit_ticket' ticket_id=ticket.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded">Editer votre Ticket</a>
            <a href="{% url 'delete_ticket' ticket_id=ticket.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 border-b-4 border-red-700 hover:border-red-500 rounded">Supprimer votre Ticket</a>
        </div>
        {% endif %}
    </div>
</div>


{% endblock content %}